kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: backend-cert
spec:
  commonName: www.<domain>.com
  dnsNames:
    - www.<domain>.com
    - <domain>
  duration: 2160h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: demo-test-root-ca
  renewBefore: 360h0m0s
  secretName: backend-secret
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 2048
