package com.example.demo.controllers;

import com.example.demo.models.Analytic;
import com.example.demo.repositories.Analytics;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/analytics") // This means URL's start with /demo (after Application path)
public class AnalyticsController {

    @Autowired // This means to get the bean called analyticsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Analytics analytics;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Analytic> getAllAnalytics() {

        // This returns a JSON or XML with the analytics
        return analytics.findAll();

    }

}