package com.example.demo.controllers;

import com.example.demo.models.Analytic;
import com.example.demo.repositories.Analytics;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/analytics") // This means URL's start with /demo (after Application path)
public class AnalyticsController {

    @Autowired // This means to get the bean called analyticsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Analytics analytics;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Analytic> getAllAnalytics() {

        // This returns a JSON or XML with the analytics
        return analytics.findAll();

    }

    @PutMapping(path="/add")
    public @ResponseBody String addAnalytic(
            @RequestParam String url,
            @RequestParam String timestamp,
            @RequestParam String useragent,
            @RequestParam String language,
            @RequestParam String geolocation
    ) {

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Analytic analytic = new Analytic();
        analytic.setURL(url);
        analytic.setTimestamp(timestamp);
        analytic.setUserAgent(useragent);
        analytic.setLanguage(language);
        analytic.setGeoLocation(geolocation);
        analytic.save(analytic);
        return "Saved";

    }

}