package com.example.demo.controllers;

import com.example.demo.models.Analytic;
import com.example.demo.repositories.Analytics;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.lang.reflect.Type;
import java.net.URISyntaxException;

@Controller // This means that this class is a Controller
@RequestMapping(path="/analytics") // This means URL's start with /demo (after Application path)
public class AnalyticsController {

    @Autowired // This means to get the bean called analyticsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Analytics analytics;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Analytic> getAllAnalytics() {

        // This returns a JSON or XML with the analytics
        return analytics.findAll();

    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewAnalytic (@RequestBody Analytic analytic) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        // @RequestBody means it is a body from the GET or POST request

        analytics.save(analytic);
        return "Saved";

    }

}