package com.springreacttypescriptrest.backend.controllers;

import com.springreacttypescriptrest.backend.models.Analytic;
import com.springreacttypescriptrest.backend.repositories.Analytics;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Collections;

@RestController // This means that this class is a Rest Controller
@RequestMapping(path="/analytics") // This means URL's start with /demo (after Application path)
public class AnalyticsController {

    @Autowired // This means to get the bean called analyticsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Analytics analytics;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Analytic> getAllAnalytics() {

        // This returns a JSON or XML with the analytics
        return analytics.findAll();

    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addAnalytic (@RequestBody Analytic analytic) {

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        // @RequestBody means it is a body from the GET or POST request

        analytics.save(analytic);

        return "Added analytic";

    }

}